# Minimal NixOS configuration for initial VirtualBox installation
# After installation, switch to flake-based config with: sudo nixos-rebuild switch --flake .#vbox

{ config, pkgs, ... }:

{
  imports = [
    # This will import the hardware-configuration.nix generated by nixos-generate-config
    /etc/nixos/hardware-configuration.nix
  ];

  # Bootloader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Enable flakes (required for switching to our flake config)
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # Network
  networking.hostName = "nixos-install";
  networking.networkmanager.enable = true;

  # Basic user
  users.users.michal = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" ];
  };

  # Enable sudo without password
  security.sudo.wheelNeedsPassword = false;

  # Minimal packages for installation
  environment.systemPackages = with pkgs; [
    git  # Required for cloning our config
    mc   # File manager
  ];

  # SSH for remote access
  services.openssh.enable = true;
  networking.firewall.allowedTCPPorts = [ 22 ];

  # VirtualBox guest additions
  virtualisation.virtualbox.guest.enable = true;

  system.stateVersion = "24.05";
}